# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Labeler
description: A GitHub action to manage Issue/PR labels
inputs:
  token:
    description: Token with pull requests/issues write permissions
    required: true
    default: ${{ github.token }}
  repository:
    description: Repository name in `owner/repo` format
    required: true
    default: ${{ github.repository }}
  issue:
    description: Issue or pull request number
    required: true
  label:
    description: Label name
    required: true
  action:
    description: |
      Action which should be performed with given label.
      Options: `add`, `remove`
    required: true
  suppress:
    description: Whether to suppress errors for failed requests or not.
    required: true
    default: 'false'

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: python
      env:
        ACTION: ${{ inputs.action }}
      run: |
        import os
        action_opts = ["remove", "add"]
        action = os.environ["ACTION"]
        if action not in action_opts:
            raise ValueError(f"Action has to be one of {action_opts}.")

    - name: Remove label `${{ inputs.label }}` from issue ${{ inputs.issue }}
      if: ${{ inputs.action == 'remove' }}
      shell: bash
      run: |
        set -e
        if gh issue --repo "$REPOSITORY" view "$ISSUE" > /dev/null 2>&1; then
          gh issue --repo "$REPOSITORY" edit "$ISSUE" --remove-label "$LABEL"
        else
          gh pr --repo "$REPOSITORY" edit "$ISSUE" --remove-label "$LABEL"
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE: ${{ inputs.issue }}
        LABEL: ${{ inputs.label }}

    - name: Add label `${{ inputs.label }}` to issue ${{ inputs.issue }}
      if: ${{ inputs.action == 'add' }}
      shell: bash
      run: |
        set -e
        if gh issue --repo "$REPOSITORY" view "$ISSUE" > /dev/null 2>&1; then
          gh issue --repo "$REPOSITORY" edit "$ISSUE" --add-label "$LABEL"
        else
          gh pr --repo "$REPOSITORY" edit "$ISSUE" --add-label "$LABEL"
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE: ${{ inputs.issue }}
        LABEL: ${{ inputs.label }}
