# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Trigger Review Project

on:
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "edited", "review_requested", "review_request_removed", "closed"]
  pull_request_review:
  pull_request_review_comment:

permissions: {}

jobs:
  trigger_project_workflow:
    permissions:
      contents: read  # Required for checking out code or referencing internal workflow actions
      pull-requests: write  # Required to modify or comment on pull requests within this pipeline process
    uses: MetOffice/growss/.github/workflows/trigger-project-workflow.yaml@main
    # secrets: inherit
