# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Fix UMDP3

on:
  workflow_call:
    inputs:
      runner:
        description: 'The runner to use for the job'
        required: false
        type: string
        default: 'ubuntu-24.04'
      timeout:
        description: 'The time limit for the workflow, default 10 minutes'
        required: false
        type: number
        default: 10

permissions:
  contents: read

jobs:
  umdp3_fixer:
    name: UMDP3 Fixer
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          path: pr_branch
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Checkout SimSys_Scripts
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v 6.0.3
        with:
          repository: MetOffice/SimSys_Scripts
          sparse-checkout: umdp3_fixer
          path: SimSys_Scripts
          persist-credentials: false

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: 3.14

      - name: Run UMDP3 Fixer
        working-directory: ./SimSys_Scripts/umdp3_fixer
        run: |
          python rosestem_branch_checker.py --source "${GITHUB_WORKSPACE}/pr_branch" --fixer_source . --col 80
