# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Validate Symlinks

on:
  workflow_call:
    inputs:
      runner:
        description: 'The runner to use for the job'
        required: false
        type: string
        default: 'ubuntu-24.04'
      timeout:
        description: 'The time limit for the workflow, default 5 minutes'
        required: false
        type: number
        default: 5

permissions:
  contents: read

jobs:
  validate_symlinks:
    name: Validate Symlinks
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Find broken symlinks
        run: |
          broken_links=$(find . -path '.git' -prune -o -xtype l -printf '%p -> %l\n' || true)
          if [ -n "$broken_links" ]; then
            echo "::error::Broken symlinks have been identified:"
            printf "%s\n" "$broken_links"
            exit 1
          fi
          echo "::notice::No broken symlinks identified."
